#!/usr/bin/env python 

import sys
import subprocess

def window(width, height, x, y):
	subprocess.call(["xdotool", "getactivewindow", "windowsize", 
					 str(width), str(height), "windowmove", 
					 str(x), str(y)])

# Config
screen_width = 3840
screen_height = 2160 - 200 # Leave room for dock
margin = 100

try:
	option = int(sys.argv[1]) - 1
	x_mod = option % 3
	y_mod = option / 3

	width = (screen_width - 4 * margin) / 3

	if y_mod == 1:
		height = (screen_height - 2 * margin)
		y_mod = 0
	else:
		height = (screen_height - 3 * margin) / 2
		if y_mod == 2:
			y_mod = 0
		else:
			y_mod = 1

	c = x_mod * (width  + margin) + margin
	d = y_mod * (height + margin) + margin

	window(width, height, c, d)
except:
	pass
